### ISSUE TITLE
Support certPath in extension

### ISSUE THREAD

**Issue by ysb33r** [gesellix/gradle-docker-plugin#41]
It would be useful to be able to set the certificate path in the `docker` i.e. 

```groovy
docker {
  // Use an object that can be evaluated with project.file()
  certPath = '/path/to/directory'
}
```

**Comment by gesellix** [comment]
note to self/todo: pass the configured `certPath` to the underlying docker-client library.

**Comment by gesellix** [comment]
closing in favour of the older #38.

**Comment by gesellix** [comment]
@ysb33r you can try the fresh release `2016-01-07T23-59-30` now. If anything's is still missing feel free to leave a note here or to create a new issue. Thanks!

**Comment by ysb33r** [comment]
There is actually still a bug and it relates to what I mentioned in #39. I'll do a PR for a change to `DockerTask` to rectify that when I get the chance - probably Monday (unless I get to code it up at the airport).

**Comment by gesellix** [comment]
If you like, you can send me a build.gradle snippet so that I can reproduce the issue. Are you creating the tasks via Gradle rules?

**Comment by ysb33r** [comment]
This might be enough to get you going.

```groovy

docker {
    dockerHost = System.getProperty('DOCKER_HOST') ?: 'https://192.168.99.100:2376'
    certPath = System.getProperty('docker.cert.path') ?: "${System.getProperty('user.home')}/.docker/machine/machines/default"
}

task verifyDockerVersion ( type : DockerTask ) {
    doFirst {
        if(!getDockerClient().version().content.Version =~ /^1\.9\./) {
            throw new GradleException("Requires Docker 1.9+")
        }
    }
}

```

**Comment by gesellix** [comment]
After adding some braces around the `Version =~ /^1\.9\./` matcher it seems to work as expected. Do you have a stacktrace?

code snippet with braces:

```
task verifyDockerVersion(type: DockerTask) {
  doFirst {
    if (!(getDockerClient().version().content.Version =~ /^1\.9\./)) {
      throw new GradleException("Requires Docker 1.9+")
    }
  }
}
```

**Comment by ysb33r** [comment]
```
Caused by: java.io.FileNotFoundException: /Users/schalkc/.docker/key.pem (No such file or directory)
	at de.gesellix.docker.client.KeyStoreUtil.loadPEM(KeyStoreUtil.groovy:40)
	at de.gesellix.docker.client.KeyStoreUtil.loadPrivateKey(KeyStoreUtil.groovy:34)
	at de.gesellix.docker.client.KeyStoreUtil$loadPrivateKey$0.callStatic(Unknown Source)
	at de.gesellix.docker.client.KeyStoreUtil.createDockerKeyStore(KeyStoreUtil.groovy:22)
	at de.gesellix.docker.client.KeyStoreUtil$createDockerKeyStore.call(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.initSSLContext(LowLevelDockerClient.groovy:333)
	at de.gesellix.docker.client.LowLevelDockerClient.initSSLSocketFactory(LowLevelDockerClient.groovy:324)
	at de.gesellix.docker.client.LowLevelDockerClient$initSSLSocketFactory$4.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.configureSSL(LowLevelDockerClient.groovy:317)
	at de.gesellix.docker.client.LowLevelDockerClient$configureSSL$3.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.configureConnection(LowLevelDockerClient.groovy:312)
	at de.gesellix.docker.client.LowLevelDockerClient.request(LowLevelDockerClient.groovy:89)
	at de.gesellix.docker.client.LowLevelDockerClient$request$1.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.get(LowLevelDockerClient.groovy:46)
	at de.gesellix.docker.client.LowLevelDockerClient$get.call(Unknown Source)
	at de.gesellix.docker.client.DockerClientImpl.version(DockerClientImpl.groovy:89)
	at de.gesellix.docker.client.DockerClient$version.call(Unknown Source)
	at build_2bznrbpputs2lcu8dx6dj63u8$_run_closure5$_closure11.doCall(/Users/schalkc/Projects/Ifu/PortaWebservice/functionalTests/build.gradle:34)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.j
```

It complains about that location not being found eventhough I told it to look somewhere else.

**Comment by gesellix** [comment]
@ysb33r thanks, I found the issue - apart from the certPath not being passed down to the SSL config, I obviously missed a test case for that one.

**Comment by gesellix** [comment]
@ysb33r this one should be fixed now with `2016-01-12T00-02-26`.

**Comment by ysb33r** [comment]
Confirmed that it did.
